## Train Test Split

## Import the relevant libraries

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split


## Generate the data we are going to split

In [8]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [12]:
train_test_split(a)

[array([54, 62, 55, 20, 87,  4,  8, 13, 58,  2, 85, 34, 61, 47, 96, 12, 30,
        32, 69, 25, 79, 19, 89, 16, 51, 38, 40, 21, 98, 31, 23,  6, 84, 88,
        52, 90, 45, 91,  3, 10, 57, 65, 81, 66,  1, 97, 43, 67, 33, 37, 68,
        83, 64, 27, 44, 39,  9, 35, 24, 59, 50, 72, 94, 46, 74, 73, 99, 28,
        78, 93, 80, 60, 77, 41, 75]),
 array([ 14,   7,  56,   5,  42,  49,  22,  48,  18,  26,  95,  29,  63,
         82,  36,  76,  70,  11, 100,  15,  86,  53,  71,  92,  17])]

In [57]:
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size = 0.2, random_state = 42)

## Explore the result 

In [59]:
a_train.shape, a_test.shape

((80,), (20,))

In [51]:
a_train

array([ 48,  84,  67,  73,   9,  78,  10,  68,  26,   3,  88,  24,  60,
        87,  17,  42,   6,   8,  49,  97,  12,  82,  85,  77,  16,  33,
        64,  66,  62,  20,  58,  36,  11,  50,  63,  95,  32,  98,  57,
        13,  65,  74,   2,  96, 100,  83,  44,  37,  52,  19,  43,  53,
        70,   1,  99,   7,   4,  61,  14,  34,  47,  90,  80,  56,  93,
         5,  38,  86,  79,  18,  28,  29,  31,  75,  25,  71,  72,  23,
        69,  89])

In [53]:
a_test

array([27, 55, 40, 92, 35, 91, 54, 81, 21, 94, 41, 59, 51, 15, 30, 39, 76,
       22, 45, 46])

In [61]:
b_train.shape, b_test.shape

((80,), (20,))

In [63]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [65]:
b_test

array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
       534, 591, 505, 577, 578, 513, 532])