## Multiple Regression with Sklearn

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [4]:
data = pd.read_csv('1.02.+Multiple+linear+regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [6]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

## Create the multiple regression

### Declare the dependent and independent variable 

In [53]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

## Standardization

In [64]:
from sklearn.preprocessing import StandardScaler

In [77]:
scaler = StandardScaler()

In [79]:
scaler.fit(x)

StandardScaler()

In [81]:
x_scaled = scaler.transform(x)

In [83]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

## Regression with scaled features

In [88]:
reg0 = LinearRegression()
reg0.fit(x_scaled,y)

LinearRegression()

In [90]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [92]:
reg.intercept_

0.29603261264909575

## Creating the summary table

In [97]:
reg_summ = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns = ['Features'])
reg_summ['Weights'] = reg.intercept_ , reg.coef_[0] , reg.coef_[1] 
reg_summ

Features   Weights
0        Bias  0.296033
1         SAT  0.001654
2  Rand 1,2,3 -0.008270

## Making predictions with weights(Standardized Coeff)

In [100]:
new_dat = pd.DataFrame(data = [[1700,2],[1800,1]],columns = ['SAT', 'Rand 1,2,3'])
new_dat

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [102]:
reg.predict(new_dat)

array([3.09051403, 3.26413803])

## Regression itself

In [15]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [19]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [21]:
reg.intercept_

0.29603261264909575

## Calculating the R-Squared

In [24]:
reg.score(x,y)

0.4066811952814282

### Formula for the adjusted R^2
$R^2_{adj.} = 1 -(1-R^2)*\frac{n-1}{n-p-1}$

In [29]:
x.shape

(84, 2)

In [31]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
adjusted_r2 =  1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134

## Feature Selection

In [34]:
from sklearn.feature_selection import f_regression

In [36]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [38]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [40]:
p_values.round(3)

array([0.   , 0.676])

## Creating a summary table

In [47]:
reg_summary = pd.DataFrame(data = x.columns.values, columns = ['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [49]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676